### PR TITLE
docs: add parameter tables generated from schemas per vendor and sensor model

### PR DESCRIPTION
**Pull request by mojomex**
## PR Type

- Improvement

## Description

:warning: Merge #194 first! :warning: 

This PR adds 
* a modified version of Autoware.Universe's [mkdocs_macros.py](https://github.com/autowarefoundation/autoware.universe/blob/main/mkdocs_macros.py) to add support for Markdown table generation from JSON schemas
* a page per vendor with common parameters
* a page per sensor with all the parameters (and value ranges) supported by that sensor

image

## Review Procedure

Render the docs and confirm the tables are complete and correct.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Review by drwnz — CHANGES_REQUESTED** [review]
Mostly looks great, some minor suggested changes.
The only other thing that I noticed, was that generally parameter tables are built from the schema except for Hesai common which has extra (very detailed) explanation.
It might be more consistent to generate Hesai common the same as the others and add an explanation below the parameter table. This could also be done for the Nebula common parameters as well.

**Comment by mojomex** [comment]
The Hesai table I can do.

For the common one, there is almost no overlap between **all** sensors, so I would have to create around 3 separate schemas to cover everything (e..g CAN vs. IP, scan_phase vs cut angle etc.). I don't think it would be a particularly nice solution.

**Comment by mojomex** [comment]
I added the Hesai table, please check @drwnz :pray: 

image

**Review by drwnz — APPROVED** [review]
LGTM, nice :)

**Pull request merged**
