### PR TITLE
perf: unpack velodyne packets in parallel

### PR DESCRIPTION
**Pull request by mebasoglu**
## PR Type

- Improvement

## Description

The issue: https://github.com/tier4/nebula/issues/61

## Review Procedure

On the `nebula_decoders` package, I have created another interface called `ParallelUnpack`. The decoder classes for each Velodyne model inherits `ParallelUnpack` alongside `VelodyneScanDecoder`.

On the `velodyne_driver.cpp`, I converted the for loop to a parallel `for_each`. The unpack method is called in parallel and every Velodyne packet unpacks into a seperate point cloud. Then, at the end, when `get_pointcloud()` is called, al the clouds are merged into a single one. Overall, the unpack process was speeded up.

## Remarks

`VLS-128` produces a lot of packets and processing it takes too much time. This improvement tends to speed up this process.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Comment by drwnz** [comment]
@mebasoglu thank you for the PR.
One request, is it possible to exclude the formatting improvements for review, so that we can more easily see the changes you have made?
I am aware that code style refactoring is required for the Velodyne drivers generally, but it would be easier to do that in a separate PR.

**Comment by mebasoglu** [comment]
Hello  @drwnz , I undid the code formatting.

**Comment by amc-nu** [comment]
We see two issues with the PR
1. Parallel encoding is always enforced. Can you please make this parallel decoding optional?
2. This PR does not consider whether the scan phase differs from 0. Can you please check the scan phase before resetting and generating the point cloud?

**Review by amc-nu — CHANGES_REQUESTED** [review]
https://github.com/tier4/nebula/pull/62#issuecomment-1713509439

**Comment by xmfcx** [comment]
If the following issue:
- https://github.com/tier4/nebula/issues/94

is resolved, then the parallelization wouldn't be necessary anymore since we wouldn't be waiting for the entire revolution to finish before starting the unpacking process.

**Comment by mojomex** [comment]
Hi @mebasoglu, thank you for your work.
We have decided to close this PR in favor of
* #148 

Our reasoning and details can be found in [this comment](https://github.com/tier4/nebula/issues/61#issuecomment-2162131531) on
* #61 

Thank you for your understanding and your continued support!

**Pull request closed without merging**
