### PR TITLE
feat: range param for hesai

### PR DESCRIPTION
**Pull request by yukkysaito**
## PR Type

- New Feature

## Description
The XT-32 has been tested and confirmed to work on the actual device.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Review by drwnz — APPROVED** [review]
LGTM!

**Comment by yukkysaito** [comment]
@drwnz @amc-nu I didn't pass one test, is that ok?
image

**Review by amc-nu — CHANGES_REQUESTED** [review]
The tests fail because the new parameter is not set, and these default to 0 in the min and max parameters.

Can you please add these two new parameters to the tests?

https://github.com/tier4/nebula/blob/main/nebula_tests/hesai/hesai_ros_decoder_test.cpp#L90

**Comment by yukkysaito** [comment]
@amc-nu It has not passed the test yet. I need help. :pray:

**Comment by amc-nu** [comment]
@yukkysaito Fixed in https://github.com/tier4/nebula/pull/121/commits/4a0371333cb067c573a494ba9b52fd0a893bb6fb

**Review by amc-nu — APPROVED** [review]

**Pull request merged**
