### PR TITLE
fix(nebula_ros): limit cloud_max_angle param to 359 #44

### PR DESCRIPTION
**Pull request by mebasoglu**
## PR Type

- Bug Fix

## Related Links

The issue: https://github.com/tier4/nebula/issues/44

## Description

This PR changes default `cloud_max_angle` to 359 and also limits `cloud_min_angle` and `cloud_max_angle` to 359. By doing those, it fixes https://github.com/tier4/nebula/issues/44 .

## Review Procedure

Range of the parameters, default values of them and readme can be checked.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Comment by drwnz** [comment]
Thank you for the PR! I see you have edited for Hesai and Velodyne - actually, Hesai sensors have a range from [0...360] whereas Velodyne sensors are typically [0...359].

**Comment by mebasoglu** [comment]
Hello, thank you for the feedback! I discarded Hesai chagnes.

**Comment by drwnz** [comment]
@mebasoglu cc @amc-nu 
Thank you for the PR- upon investigation, unfortunately we can't limit Velodyne max angle to 360 degrees as it is used in software clipping so doing so results in a 1 degree gap in the cloud.
I will address this issue in a different PR.

**Comment by drwnz** [comment]
@mebasoglu 
Can you please test with this PR?
https://github.com/tier4/nebula/pull/50

If that fixes the issue then we can close this PR. Thank you.

**Comment by mebasoglu** [comment]
Hello, I tested and it works, thank you.

**Pull request closed without merging**
