### PR TITLE
fix(hesai_hw_interface): hesai interface

### PR DESCRIPTION
**Pull request by amc-nu**
## PR Type

- Improvement

## Related Links

https://tier4.atlassian.net/browse/RT1-3200
https://tier4.atlassian.net/browse/RT1-3111

## Description

Improves reliability of Hesai HW Interface.:
- Allows `sensor_setup:=False`
- Removes crashing when sensor not available or timeout.

Includes the following features:

* Gets LidarCalibration from sensor
* Skips GetInventory if unable to connect.
* Fixes Hesai monitor.
* Check calibration file format AT128.
* Saves calibration data from sensor.
* Fallback to offline mode AT128
* Checks Return Mode AT128

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Review by drwnz — COMMENTED** [review]
When restarting the driver multiple times with the device connected, after the 4th attempt I get this warning:
```[component_container-1] [WARN] [1697789855.726097568] [hesai_hw_monitor_ros_wrapper_node]: diagnostic_updater: No HW_ID was set. This is probably a bug. Please report it. For devices that do not have a HW_ID, set this value to 'none'. This warning only occurs once all diagnostics are OK. It is okay to wait until the device is open before calling setHardwareID.```

This is coming from diagnostic updater - I guess this is related to the TCP connection limitation we discussed? FYI this is on the AT128.
The device still works, and the configuration also seems to stick so not a major issue.

**Comment by amc-nu** [comment]
Yes, exactly. The sensor stops receiving commands.

**Comment by drwnz** [comment]
> Yes, exactly. The sensor stops receiving commands.

It does seem to still correctly configure the sensor though?

**Comment by amc-nu** [comment]
It configures the sensor only during the first attempts. Afterwards the sensor rejects all the connections.

**Comment by drwnz** [comment]
I will merge this PR and we can work on the TCP rejection issue in a different PR.
Thank you for the great work, DAT file download works well.

**Review by drwnz — APPROVED** [review]

**Pull request merged**
