### PR TITLE
fix(nebula_examples): fix lint errors. Add ament_lint dependencies

### PR DESCRIPTION
**Pull request by esteve**
## PR Type

- Bug Fix

## Description

This PR fixes the lint errors and enables the linters in `package.xml`

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

### CODE REVIEW

**Comment by esteve** [comment]
@amc-nu this PR adds the changes from #65 and also fixes the lint errors in CMake and the C++ code.

**Comment by amc-nu** [comment]
Thank you for this PR.
We have a few PRs pending. I’m sure linting will cause many errors. Do you suggest any automatic linting tool?
Thanks again

**Comment by esteve** [comment]
@amc-nu I've used the ones that come with `ament_lint`, unfortunately some of the lints can't be fixed automatically (e.g. `lint_cmake`, `cpplint`), but for formatting I just used `ament_uncrustify --reformat`

I've noticed that `clang-tidy` fails, but I don't know if that's a required check.

**Comment by amc-nu** [comment]
Indeed, we don't enforce clang-tidy since it fails consistently on rclcpp.

**Comment by esteve** [comment]
@amc-nu no problem, let me remove the latest changes and then the PR should be ready for review. I was hoping I could fix the clang-tidy issues, but couldn't figure out a way to ignore rclcpp

**Comment by esteve** [comment]
@amc-nu I've removed all the attempts to fix the clang-tidy issues, this PR is now ready for review.

**Review by amc-nu — APPROVED** [review]

**Pull request merged**
